export const metadata = {
  title: 'Members from external Source',
  description: 'Generated by Hakim',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
